### ISSUE TITLE
"Chrome could not start (or has crashed) after 5 seconds."

### ISSUE THREAD

**Issue by developer-bro** [symfony/panther#208] opened 2019-07-01 18:52 UTC
I got this error on production server. Im running on AWS ubuntu 18.04 instance.

request.CRITICAL: Uncaught PHP Exception RuntimeException: "Chrome could not start (or has crashed) after 5 seconds." at /vendor/symfony/panther/src/ProcessManager/WebServerReadinessProbeTrait.php:51)"} []

**Comment by dunglas** [comment] 2019-07-01 19:04
Probably a duplicate of https://github.com/symfony/panther/issues/200. Can you try if increasing the timeout as described in this issue helps?

**Comment by developer-bro** [comment] 2019-07-03 00:17
No luck increasing the timeout.

same error again.

Uncaught PHP Exception RuntimeException: "Chrome could not start (or has crashed) after 30 seconds."

**Comment by lyrixx** [comment] 2019-07-08 14:22
Could you try master, and tell me what error message you get?

**Comment by vasilvestre** [comment] 2019-07-12 13:10
Same situation, full message is (RuntimeException: Could not connect to chrome after 5 seconds (Invalid or missing HTTP status line.).
May not be related

**Closed** 2019-08-21 10:42 UTC
